FORMAT: 1A
HOST: https:/www.ahem.email/api/

# AHEM - Ad Hoc Email

AHEM is an ad hoc disposable and temporary email service. It allows receiving email at an ad-hoc created email, created on the fly when an email is received by our server.
Using the AHEM service allows you to prevent spam to your real email, and to test products that send email as part of their lifecycle.

## Properties [/properties]

### List system wide properties [GET]
+ Response 200 (application/json)

        {
            "serverBaseUri":"https://www.ahem.email",
            "emailDeleteInterval":86400,
            "emailDeleteAge":7200,
            "allowedDomains":[
                "ahem.email",
                "mail.ahem.email",
                "ahem-email.com"
                ],
            "allowAutocomplete":false,
            "customText": null
        }




## Account's Email List [/accout/{accountName}]

### List All Emails in an account [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }